# temperature_pb2_grpc.py
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import temperature_pb2 as temperature__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in temperature_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TemperatureServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.uno_uno = channel.unary_unary(
                '/temperature.TemperatureService/uno_uno',
                request_serializer=temperature__pb2.TemperatureRequest.SerializeToString,
                response_deserializer=temperature__pb2.TemperatureResponse.FromString,
                _registered_method=True)
        self.uno_muchos = channel.unary_stream(
                '/temperature.TemperatureService/uno_muchos',
                request_serializer=temperature__pb2.TemperatureRequest.SerializeToString,
                response_deserializer=temperature__pb2.TemperatureResponse.FromString,
                _registered_method=True)
        self.muchos_uno = channel.stream_unary(
                '/temperature.TemperatureService/muchos_uno',
                request_serializer=temperature__pb2.TemperatureRequest.SerializeToString,
                response_deserializer=temperature__pb2.TemperatureResponse.FromString,
                _registered_method=True)
        self.muchos_muchos = channel.stream_stream(
                '/temperature.TemperatureService/muchos_muchos',
                request_serializer=temperature__pb2.TemperatureRequest.SerializeToString,
                response_deserializer=temperature__pb2.TemperatureResponse.FromString,
                _registered_method=True)


class TemperatureServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def uno_uno(self, request, context):
        """uno a uno
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def uno_muchos(self, request, context):
        """uno a muchos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def muchos_uno(self, request_iterator, context):
        """muchos a uno
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def muchos_muchos(self, request_iterator, context):
        """muchos a muchos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemperatureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'uno_uno': grpc.unary_unary_rpc_method_handler(
                    servicer.uno_uno,
                    request_deserializer=temperature__pb2.TemperatureRequest.FromString,
                    response_serializer=temperature__pb2.TemperatureResponse.SerializeToString,
            ),
            'uno_muchos': grpc.unary_stream_rpc_method_handler(
                    servicer.uno_muchos,
                    request_deserializer=temperature__pb2.TemperatureRequest.FromString,
                    response_serializer=temperature__pb2.TemperatureResponse.SerializeToString,
            ),
            'muchos_uno': grpc.stream_unary_rpc_method_handler(
                    servicer.muchos_uno,
                    request_deserializer=temperature__pb2.TemperatureRequest.FromString,
                    response_serializer=temperature__pb2.TemperatureResponse.SerializeToString,
            ),
            'muchos_muchos': grpc.stream_stream_rpc_method_handler(
                    servicer.muchos_muchos,
                    request_deserializer=temperature__pb2.TemperatureRequest.FromString,
                    response_serializer=temperature__pb2.TemperatureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'temperature.TemperatureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('temperature.TemperatureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TemperatureService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def uno_uno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperature.TemperatureService/uno_uno',
            temperature__pb2.TemperatureRequest.SerializeToString,
            temperature__pb2.TemperatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def uno_muchos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/temperature.TemperatureService/uno_muchos',
            temperature__pb2.TemperatureRequest.SerializeToString,
            temperature__pb2.TemperatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def muchos_uno(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/temperature.TemperatureService/muchos_uno',
            temperature__pb2.TemperatureRequest.SerializeToString,
            temperature__pb2.TemperatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def muchos_muchos(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/temperature.TemperatureService/muchos_muchos',
            temperature__pb2.TemperatureRequest.SerializeToString,
            temperature__pb2.TemperatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
