# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temperature.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'temperature.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11temperature.proto\x12\x0btemperature\"\'\n\x12TemperatureRequest\x12\x11\n\tcity_code\x18\x01 \x01(\t\"+\n\x13TemperatureResponse\x12\x14\n\x0ctemperatures\x18\x01 \x03(\x02\x32\xe0\x02\n\x12TemperatureService\x12L\n\x07uno_uno\x12\x1f.temperature.TemperatureRequest\x1a .temperature.TemperatureResponse\x12Q\n\nuno_muchos\x12\x1f.temperature.TemperatureRequest\x1a .temperature.TemperatureResponse0\x01\x12Q\n\nmuchos_uno\x12\x1f.temperature.TemperatureRequest\x1a .temperature.TemperatureResponse(\x01\x12V\n\rmuchos_muchos\x12\x1f.temperature.TemperatureRequest\x1a .temperature.TemperatureResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPERATUREREQUEST']._serialized_start=34
  _globals['_TEMPERATUREREQUEST']._serialized_end=73
  _globals['_TEMPERATURERESPONSE']._serialized_start=75
  _globals['_TEMPERATURERESPONSE']._serialized_end=118
  _globals['_TEMPERATURESERVICE']._serialized_start=121
  _globals['_TEMPERATURESERVICE']._serialized_end=473
# @@protoc_insertion_point(module_scope)
